config/routes.rb
Rails.application.routes.draw do
  resources :customer_journeys
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer_journey.rb
class CustomerJourney < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :customerJourneys
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customer_journeys_controller.rb
class CustomerJourneysController < ApplicationController
  before_action :set_customer_journey, only: [:show, :edit, :update, :destroy]

  # GET /customer_journeys
  # GET /customer_journeys.json
  def index
    @customer_journeys = CustomerJourney.all
  end

  # GET /customer_journeys/1
  # GET /customer_journeys/1.json
  def show
  end

  # GET /customer_journeys/new
  def new
    @customer_journey = CustomerJourney.new
  end

  # GET /customer_journeys/1/edit
  def edit
  end

  # POST /customer_journeys
  # POST /customer_journeys.json
  def create
    @customer_journey = CustomerJourney.new(customer_journey_params)

    respond_to do |format|
      if @customer_journey.save
        format.html { redirect_to @customer_journey, notice: 'Customer journey was successfully created.' }
        format.json { render :show, status: :created, location: @customer_journey }
      else
        format.html { render :new }
        format.json { render json: @customer_journey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customer_journeys/1
  # PATCH/PUT /customer_journeys/1.json
  def update
    respond_to do |format|
      if @customer_journey.update(customer_journey_params)
        format.html { redirect_to @customer_journey, notice: 'Customer journey was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer_journey }
      else
        format.html { render :edit }
        format.json { render json: @customer_journey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customer_journeys/1
  # DELETE /customer_journeys/1.json
  def destroy
    @customer_journey.destroy
    respond_to do |format|
      format.html { redirect_to customer_journeys_url, notice: 'Customer journey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer_journey
      @customer_journey = CustomerJourney.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_journey_params
      params.require(:customer_journey).permit(:name, :description, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer_journeys_helper.rb
module CustomerJourneysHelper
end

app/views/customer_journeys/_form.html.erb
<%= form_for(customer_journey) do |f| %>
  <% if customer_journey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer_journey.errors.count, "error") %> prohibited this customer_journey from being saved:</h2>

      <ul>
      <% customer_journey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customer_journeys/edit.html.erb
<h1>Editing Customer Journey</h1>

<%= render 'form', customer_journey: @customer_journey %>

<%= link_to 'Show', @customer_journey %> |
<%= link_to 'Back', customer_journeys_path %>

app/views/customer_journeys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customer Journeys</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customer_journeys.each do |customer_journey| %>
      <tr>
        <td><%= customer_journey.name %></td>
        <td><%= customer_journey.description %></td>
        <td><%= customer_journey.user %></td>
        <td><%= link_to 'Show', customer_journey %></td>
        <td><%= link_to 'Edit', edit_customer_journey_path(customer_journey) %></td>
        <td><%= link_to 'Destroy', customer_journey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer Journey', new_customer_journey_path %>

app/views/customer_journeys/new.html.erb
<h1>New Customer Journey</h1>

<%= render 'form', customer_journey: @customer_journey %>

<%= link_to 'Back', customer_journeys_path %>

app/views/customer_journeys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer_journey.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @customer_journey.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @customer_journey.user %>
</p>

<%= link_to 'Edit', edit_customer_journey_path(@customer_journey) %> |
<%= link_to 'Back', customer_journeys_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Journey</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>